/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanookreporter;

import javax.swing.JOptionPane;

/**
 *
 * @author leggettr
 */
public class OptionsDialog extends javax.swing.JDialog {
    private NanoOKReporterOptions options;
    
    /**
     * Creates new form optionsDialog
     */
    public OptionsDialog(NanoOKReporter parent, NanoOKReporterOptions o) {
        super(parent, true);
        options = o;
        initComponents();
        NanoOKReporter.centreWindowInParent(this, parent);
        lcaMaxETextfield.setText(Double.toString(options.getLCAMaxE()));
        lcaMinIDTextfield.setText(Double.toString(options.getLCAMinID()));
        lcaMinLengthTextfield.setText(Integer.toString(options.getLcaMinLength()));
        walkoutMaxETextfield.setText(Double.toString(options.getWalkoutMaxE()));
        walkoutMinIDTextfield.setText(Double.toString(options.getWalkoutMinID()));
        walkoutMinLengthTextfield.setText(Integer.toString(options.getWalkoutMinLength()));
        maxChunkTextfield.setText(Integer.toString(options.getWalkoutMaxChunk()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lcaMaxETextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lcaMinIDTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lcaMinLengthTextfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        walkoutMaxETextfield = new javax.swing.JTextField();
        walkoutMinIDTextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        walkoutMinLengthTextfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        maxChunkTextfield = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LCA parameters"));

        jLabel1.setText("Max e-value:");

        lcaMaxETextfield.setText("0");
        lcaMaxETextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcaMaxETextfieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Min identity:");

        lcaMinIDTextfield.setText("0");
        lcaMinIDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcaMinIDTextfieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Min length:");

        lcaMinLengthTextfield.setText("0");
        lcaMinLengthTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcaMinLengthTextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lcaMaxETextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lcaMinIDTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcaMinLengthTextfield))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lcaMaxETextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lcaMinIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcaMinLengthTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Walkout parameters"));

        jLabel4.setText("Max e-value:");

        walkoutMaxETextfield.setText("0");
        walkoutMaxETextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkoutMaxETextfieldActionPerformed(evt);
            }
        });

        walkoutMinIDTextfield.setText("0");
        walkoutMinIDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkoutMinIDTextfieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Min identity:");

        jLabel6.setText("Min length:");

        walkoutMinLengthTextfield.setText("0");
        walkoutMinLengthTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkoutMinLengthTextfieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Max chunk:");

        maxChunkTextfield.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walkoutMaxETextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(walkoutMinLengthTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(maxChunkTextfield)
                    .addComponent(walkoutMinIDTextfield))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(walkoutMaxETextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walkoutMinIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walkoutMinLengthTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxChunkTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setDefaultCapable(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lcaMaxETextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcaMaxETextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcaMaxETextfieldActionPerformed

    private void lcaMinIDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcaMinIDTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcaMinIDTextfieldActionPerformed

    private void lcaMinLengthTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcaMinLengthTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcaMinLengthTextfieldActionPerformed

    private void walkoutMaxETextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkoutMaxETextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_walkoutMaxETextfieldActionPerformed

    private void walkoutMinIDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkoutMinIDTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_walkoutMinIDTextfieldActionPerformed

    private void walkoutMinLengthTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkoutMinLengthTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_walkoutMinLengthTextfieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        double newLcaMaxE = Double.parseDouble(lcaMaxETextfield.getText());
        double newLcaMinId = Double.parseDouble(lcaMinIDTextfield.getText());
        int newLcaMinLength = Integer.parseInt(lcaMinLengthTextfield.getText());

        if ((options.getLCAMaxE() != newLcaMaxE) ||
            (options.getLCAMinID() != newLcaMinId) ||
            (options.getLcaMinLength() != newLcaMinLength)) {
            JOptionPane.showMessageDialog(this, "<html><body><p style='width: 200px;'>"+"Warning: you have changed the LCA parameters. The taxonomy and list views will only take account of this option when loading data. You may need to restart for it to take effect on all your data."+"</p></body></html>", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        options.setLCAMaxE(newLcaMaxE);
        options.setLCAMinID(newLcaMinId);
        options.setLcaMinLength(newLcaMinLength);
        options.setWalkoutMaxE(Double.parseDouble(walkoutMaxETextfield.getText()));
        options.setWalkoutMinID(Double.parseDouble(walkoutMinIDTextfield.getText()));
        options.setWalkoutMinLength(Integer.parseInt(walkoutMinLengthTextfield.getText()));
        options.setWalkoutMaxChunk(Integer.parseInt(maxChunkTextfield.getText()));        
        options.writePrefs(options.getLastSample());
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lcaMaxETextfield;
    private javax.swing.JTextField lcaMinIDTextfield;
    private javax.swing.JTextField lcaMinLengthTextfield;
    private javax.swing.JTextField maxChunkTextfield;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField walkoutMaxETextfield;
    private javax.swing.JTextField walkoutMinIDTextfield;
    private javax.swing.JTextField walkoutMinLengthTextfield;
    // End of variables declaration//GEN-END:variables
}
